apiVersion: v1
kind: Service
metadata:
  name: bsf-nbsf
  labels:
    app: open5gs
    nf: bsf
spec:
  ports:
    - name: sbi
      port: 80
  selector:
    app: open5gs
    nf: bsf
---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: bsf-nbsf