apiVersion: v1
kind: Service
metadata:
  name: nrf-nnrf
  labels:
    app: open5gs
    nf: nrf
spec:
  ports:
    - name: sbi
      port: 80
  selector:
    app: open5gs
    nf: nrf
---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: nrf-nnrf